theme: minima
title: Game development research project
author: Aalo Kuuspalo
description: In this blog I will be documenting my research on game development. This project is a part of my University studies.
